FIND_PATH(HELLO_INCLUDE_DIR hello.h /home/red/Learn_projects/learn_cmake/test/include/hello)
FIND_LIBRARY(HELLO_LIBRARY hello PATH /home/red/Learn_projects/learn_cmake/test/lib)
IF(HELLO_INCLUDE_DIR AND HELLO_LIBRARY)
    SET(HELLO_FOUND TRUE)
ENDIF(HELLO_INCLUDE_DIR AND HELLO_LIBRARY)

IF(HELLO_FOUND)
    IF(NOT HELLO_FOUND_QUITELY)
        MESSAGE(STATUS "Found Hello :${HELLO_LIBRARY}")
    ENDIF(NOT HELLO_FOUND_QUITELY)
ELSE(HELLO_FOUND)
    IF(HELLO_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find hello library")
    ENDIF(HELLO_FIND_REQUIRED)
ENDIF(HELLO_FOUND)


